[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-D", "warnings", "-D", "clippy::pedantic", "-D", "clippy::unwrap_used"]

[tasks.v1]
run_task = [
    { name = ["format", "clippy", "build", "test"], condition = { files_modified = { input = ["./Cargo.toml", "./src/**/*.rs"], output = ["./target/**/mina-governance-server"] } } },
]


